name: Production Build
on: 
  push:
   branches:
      - master
jobs:
  build:
    runs-on: node-14.17.3-buster
    
    strategy:
      matrix:
        node-version: [14.x]
        
    steps:
    - uses: actions/checkout@v1
    - run: npm install 
    - run: npm run build:dev
    - run: npm install -g serve
