name: Production Build
on: 
  push:
   branches: [master]
jobs:
  build:
    runs-on: ubuntu:latest
    container: node:latest
    
    strategy:
      matrix:
        node-version: [14.x]
        
    steps:
    - uses: actions/checkout@v2
    - run: npm install 
    - run: npm run build:dev
    - run: npm install -g serve
